README.md
Every contribution to sewer is as important to us.                       
Now,
=> use shell highlight

setup.py, sewer/ACMEclient.py
- add a unique user-agent to identify this acme-client
- to comply with …
=> Add user agent

README.md, sewer/ACMEclient.py, sewer/__init__.py, sewer/__version__.py, sewer/cli.py, sewer/dns_providers/__init__.py
- improve api and make it simpler
- simplicity is cool
=> Improve api

Vagrantfile, vagrant_provision.sh
- add vagrant file
- to have reproducible dev setups
=> add vagrant for dev setup

README.md, sewer/__version__.py, sewer/cli.py
- add a --version cmd option
- fix …
=> add --version commandline option

.circleci/codecov.yml, .circleci/config.yml
- add code coverage to ci
- to guard against overage regressions
- fix …
=> add codecov

.circleci/codecov.yml
=> test codecov from master

README.md, sewer/ACMEclient.py, sewer/__version__.py, sewer/cli.py, sewer/tests/test_ACMEclient.py
- added support for SAN certificates
- fix: …
=> add support for SAN certificates

.gitignore, README.md, sewer/__version__.py, sewer/cli.py, sewer/client.py, sewer/dns_providers/auroradns.py, sewer/dns_providers/cloudflare.py, sewer/dns_providers/common.py, sewer/dns_providers/tests/test_common.py, sewer/tests/test_Client.py, sewer/tests/test_utils.py
- support SAN in acmev2
- compat with old sewere versions
=> Acmev2 san

README.md, sewer/cli.py, sewer/client.py, sewer/dns_providers/cloudflare.py, sewer/dns_providers/tests/test_cloudflare.py, sewer/dns_providers/tests/test_utils.py
=> Simpler cloudflare

README.md, setup.py, sewer/cli.py, sewer/client.py, sewer/dns_providers/auroradns.py, sewer/dns_providers/cloudflare.py, sewer/dns_providers/common.py
- use stdlib logging only
- best practices
=> use stdlib logging

Makefile, README.md, sewer/dns_providers/acmedns.py, sewer/dns_providers/tests/test_acmedns.py, sewer/dns_providers/tests/test_utils.py
- add tests for acmeDNS
- autopep8
=> Acme dns tests

.circleci/config.yml, setup.py
- pin versions of static analysis tools
- …
=> pin static analysis tools

.circleci/config.yml, .gitignore, README.md, setup.py, sewer/__init__.py, sewer/__version__.py, sewer/cli.py, sewer/client.py, sewer/config.py, sewer/dns_providers/__init__.py, sewer/dns_providers/aliyundns.py, sewer/dns_providers/tests/test_aliyundns.py, sewer/tests/test_Client.py
dns_providers: add aliyun/alicloud support
Aliyun/Alicloud is a popular …
=> dns_providers: add aliyun/alicloud support

.circleci/config.yml, README.md, setup.py, sewer/dns_providers/aliyundns.py
=> Gate aliyun

CONTRIBUTORS.md, README.md, setup.py, sewer/__init__.py, sewer/cli.py, sewer/dns_providers/__init__.py, sewer/dns_providers/rackspace.py, sewer/dns_providers/tests/test_rackspace.py
Added rackspace dns support
It's what I use and it's part of this …
=> Added Rackspace DNS 

sewer/__init__.py, sewer/cli.py, sewer/dns_providers/__init__.py, sewer/dns_providers/dnspod.py, sewer/dns_providers/tests/test_dnspod.py
=> support DNSPod dns

CONTRIBUTORS.md, setup.py, sewer/__version__.py
- create a new version
- for the fix brought in by: …
=> add new contributor

CONTRIBUTORS.md, README.md, setup.py, sewer/__init__.py, sewer/cli.py, sewer/dns_providers/__init__.py, sewer/dns_providers/cloudns.py, sewer/dns_providers/tests/test_cloudns.py
Added support for ClouDNS provider.
=> Adds support for ClouDNS (https://www.cloudns.net/)

setup.py, sewer/__init__.py, sewer/dns_providers/__init__.py, sewer/dns_providers/route53.py, sewer/dns_providers/tests/test_route53.py
- Add new DNS provider support, AWS Route53
- I use Route53 service.
- Fixes: https://github.com/komuw/sewer/issues/29
=> Support AWS Route53

CHANGELOG.md, CONTRIBUTORS.md, README.md, sewer/__version__.py, sewer/dns_providers/tests/test_dnspod.py
=> new release

sewer/dns_providers/aliyundns.py
closes: https://github.com/komuw/sewer/issues/132
=> Bugfixed: fixed aliyundns return is bytes

CHANGELOG.md, sewer/__version__.py
=> create new release

README.md
=> Fix DNS provider names in README

sewer/auth.py, sewer/cli.py, sewer/client.py, sewer/dns_providers/acmedns.py, sewer/dns_providers/cloudflare.py, sewer/dns_providers/rackspace.py, sewer/lib.py
I still blame @AlecTroemel , but let's not forget Codacy's part in pointing out the chunk of near-duplicated code used for setting up logging.  Another rather trivial refactoring that I hope meets with your approval, extending #169
=> Hoisted log_response and log setup (as create_log)

CHANGELOG.md, README.md, setup.py, sewer/client.py
Works to issue certificate from staging environment.
=> ACME protocol updates (RFC8555)

docs/CHANGELOG.md, docs/README.md, docs/dns-01.md, docs/index.md, docs/notes/0.8.3-notes.md, setup.py, sewer/catalog.json, sewer/cli.py, sewer/client.py, sewer/lib.py, sewer/meta.json, sewer/tests/test_lib.py
warning about Python version required (3.5 iffy); formatted catalog.json
dropped pandoc (all it needed was the right long_description_content_type)
sewer.json renamed meta.json; setup.py now depends on meta and the catalog!
=> Final 0.8.3 changes

.github/workflows/build.yml, README.md, pyproject.toml, setup.py
- Add GitHub actions workflow
- Update Python versions to those that are currently supported
Ensure code works with current releases of python and current releases of dependencies
=> WIP: Update testing to use GitHub actions
