- setup.py
- sewer/ACMEclient.py
Every contribution to sewer is as important to us.                       
- change letsencrypt urls to production ones
- make customers …
> Ready prod

- setup.py
- sewer/ACMEclient.py
- sewer/__version__.py
- sewer/cli.py
- sewer/dns_providers/cloudflare.py
- sewer/dns_providers/common.py
- make the acme client to be dns provider agnostic
- to be able to …
> Dns provider agnostic

- sewer/__version__.py
- sewer/cli.py
- add ability to specify bundle name
- you may be using a webserver …
> Specify bundlename

- sewer/__version__.py
- sewer/cli.py
- use specified bundle_name in certificate and certificate key names.
- …
> use provide bundle_name as is in certificate and certificate key names

- sewer/ACMEclient.py
- sewer/__version__.py
- log certificate get response
- use a generic log method
- for full …
> fix certificate logging bug

- README.md
- sewer/ACMEclient.py
- sewer/tests/test_ACMEclient.py
- rename certicate to certificate
- use proper english names
- fix …
> fix cert naming typo

- .circleci/config.yml
- .github/CONTRIBUTING.md
- CONTRIBUTORS.md
- setup.py
- sewer/__init__.py
- sewer/cli.py
- sewer/dns_providers/__init__.py
- sewer/dns_providers/auroradns.py
Added support for AuroraDns.
Would like to see support for this dns …
> Adding support for AuroraDNS

- sewer/ACMEclient.py
- sewer/tests/test_ACMEclient.py
- sewer/tests/test_utils.py
- only get certificates if certificate is valid.
- fixes: …
> only get certificates if no errors

- sewer/__version__.py
- sewer/cli.py
- made parser add arguments' choices field to be a list
- fix: …
> bugfix: cli unable to acquire certificates.

- sewer/dns_providers/cloudflare.py
Explicit JSON serialization can be performed by `requests` since https://github.com/requests/requests/commit/8f17741 (July 2014), thus pushing such functionality leads to cleaner code. I also removed (presumably) copy-pasted `Content-Type` headers from requests without any body at all (`GET` and `DELETE`).
> CloudFlareDns: requests have built-in support for json

- .circleci/config.yml
- README.md
- setup.py
- sewer/__init__.py
- sewer/cli.py
- sewer/dns_providers/__init__.py
- sewer/dns_providers/acmedns.py
[acme-dns](https://github.com/joohoi/acme-dns) is a simplified DNS server with a RESTful HTTP API to provide a simple way to automate ACME DNS challenges. This PR adds the necessary class to use any 3rd party or self-hosted _acme-dns_ instance with _sewer_. I tested this in the staging environment with my own domain running my own _acme-dns_ instance, and it generated the certificate successfully.
> Support acme-dns

- sewer/cli.py
- sewer/client.py
I added an option to the `Client` constructor named `certificate_key` which behaves just like the optional parameter `account_key` -- it allows the user to specify a private key instead of generating one.
While I'm all for generating new keys upon each renewal as it dramatically lowers the time window in which a leaked key can be abused, there are situations when a pre-existing key must be used.
For example if [HPKP](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) is already set up and clients expects private keys to be selected from a limited pool already advertised in the header, there's no other option but to generate a certificate that matches at least one of the entries already known by User-Agents.
> Allow certificate_key to be specified like account_key

- sewer/client.py
- sewer/tests/test_Client.py
- sewer/tests/test_utils.py
I've changed some of the logic in `get_certificate` to call `check_authorization_status()` twice instead of just once. There are a couple of reasons for this:
- After submitting a challenge response, the client wasn't waiting for the authorization to transition to the `valid` status, if it was in the `pending` status before that. The ACME server might have not had enough time to run the validation of the DNS challenge to transition the authorization to the `valid` state.
- An authorization could have been successfully handled by a previous run of sewer for a hostname or set of hostnames. LetsEncrypt in particular caches valid authorizations for 30 days, so if you're requesting a new certificate for a hostname which you had already proved ownership, recently, then you should not submit a …
> check authorizations after challenge responses

- sewer/dns_providers/common.py
Added logger name under common.py providers path that identify the package.
I proposed this patch because, by default, each call to the logger is identified with "root" name.
this edit is useful when the package is used inside another one considering that, we can identify easily the log provenience.
> Added logger name that identify the package

- sewer/dns_providers/duckdns.py
added provider name checking in domain_name string for DuckDNS.
Because in the Home Assistant plugin parameter for duckdns we can add domain name with and without the string part of the provider name. (i'm working on the plugin)
> added provider name checking in domain_name string

- sewer/client.py
I moved the wait period to the beginning of the loop, before the first …
> Moves sleep before the initial verification call.

- sewer/client.py
- sewer/dns_providers/common.py
Loggers used by sewer.
The client is redefining root logger. It should not as it's messing with any project importing sewer and already having a logging system in place.
In a project with a lot of sub-modules, the general logging level is set at the root logger level and propagated to all sub-logger of each sub-modules (using `logging.getLogger(__name__)`).
But then, let's say you want to create a sewer client with only error logging level while the rest is at info, you would run something like `sewer.Client(..., LOG_LEVEL="ERROR")` but this will change ALL the other loggers that are completely unrelated to sewer to ERROR too(!) as they are children of the root logger.
Also, it probably doesn't make sense to use a named logger like `logging.getLogger("sewer")` as the logger is already …
> Fix logging

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTORS.md
- sewer/cli.py
- sewer/dns_providers/cloudflare.py
- sewer/dns_providers/route53.py
- sewer/dns_providers/tests/test_cloudflare.py
You may not know it, but you have just contributed to making the world a more safer and secure place.
- Added support for tokens in Cloudflare DNS
- Fixed how Route53 imports dependencies
- Tokens …
> Add Cloudflare token auth support and fix Route53 imports

- CONTRIBUTORS.md
- sewer/client.py
Changed the order of checks.
Found a bug where the last GET response was not evaluated (but logged) before raising a StopIteration exception. Although the last response had a "valid" status, sewer still raised the exception.
This way the while loop does not terminate prematurely before checking the last request's status.
> Fix authorization status checker to check the last request before StopIteration

- .github/CONTRIBUTING.md
- CHANGELOG.md
- sewer/__version__.py
- sewer/dns_providers/cloudflare.py
- if we have been given a wildcard name, strip wildcard before trying …
> lstrip domain name if wildacrd

- setup.py
- sewer/dns_providers/tests/test_acmedns.py
- sewer/dns_providers/tests/test_aliyundns.py
- sewer/dns_providers/tests/test_aurora.py
- sewer/dns_providers/tests/test_cloudflare.py
- sewer/dns_providers/tests/test_cloudns.py
- sewer/dns_providers/tests/test_dnspod.py
- sewer/dns_providers/tests/test_duckdns.py
- sewer/dns_providers/tests/test_hedns.py
- sewer/dns_providers/tests/test_rackspace.py
- sewer/dns_providers/tests/test_route53.py
- sewer/tests/test_Client.py
> Use unittest.mock in place of external module.  Requires Python 3.3+

- README.md
- setup.py
- sewer/__init__.py
- sewer/cli.py
- sewer/dns_providers/__init__.py
- sewer/dns_providers/powerdns.py
- sewer/dns_providers/tests/test_powerdns.py
Added a dns provider for the PowerDNS API.
So that DNS authentication can be performed against a PowerDNS server.
> PowerDNS dns provider.

- sewer/client.py
Cleaned up request wrappers without unnecessary complications.
Prepares for running sewer against pebble server as discussed in #152.
> Wrap requests.[get,head,post] calls

- sewer/dns_providers/tests/test_powerdns.py
Added unittest.mock change to test_powerdns.py in order to fix CI failure.
> Trivial: add unittest.mock change to powerdns driver

- sewer/dns_providers/route53.py
Fix obvious bug in `route53.__init__`, missing self in super().
Reported and fix suggested and tested by @hobosteaux.
> BUG FIX #168 - added missing self arg in route53's super()

- README.md
- sewer/__init__.py
- sewer/cli.py
- sewer/dns_providers/__init__.py
- sewer/dns_providers/gandi.py
- sewer/dns_providers/tests/test_gandi.py
Added a dns_provider class for the gandi DNS service
+ tests (although …
> Gandi DNS service

- sewer/tests/test_Client.py
While helping a new contributor, I found myself writing "it would be better if test were run at log level WARNING".  And so it would...
> run test_Client with log level WARNING to reduce spew

- sewer/tests/test_auth.py
I don't know if I was just blind or if it really wasn't showing me the coverage map for auth.py before the merge.  Obviously missed that last-added feature.
> add missing tests for prop_* options (for 0.8.2)

- README.md
- sewer/cli.py
This is the enhancement @menduo presented in #154 lightly revised.  Biggest change is to the option name, which is --acme_timeout rather than just --timeout because there are already other timeouts that may need to be accessible through a sewer-cli option.
> Add --acme_timout option to sewer-cli

- CONTRIBUTORS.md
- sewer/dns_providers/gandi.py
- sewer/dns_providers/tests/test_gandi.py
Changed the name used to create and remove TXT records with Gandi when authorizing 2nd-level domains.
Before this change, sewer failed to manage domains like "example.com" and its wildcard equivalent "*.example.com". Any such attempt would result in an HTTP error during creation of a TXT record. 
This was because sewer would attempt to create a TXT record under the name "_acme-challenge.@", whereas Gandi requires "_acme-challenge".
> Fix failure to manage 2nd-level domains with Gandi

- docs/CHANGELOG.md
- docs/catalog.md
- docs/dns-01.md
- docs/drivers/route53.md
- docs/drivers/unbound_ssh.md
- docs/notes/0.8.3-notes.md
- setup.py
- sewer/__version__.py
- sewer/catalog.json
- sewer/catalog.py
- sewer/cli.py
- sewer/client.py
- sewer/dns_providers/tests/test_unbound_ssh.py
- sewer/lib.py
- sewer/sewer.json
- sewer/tests/test_catalog.py
- sewer/tests/test_lib.py
Add catalog.json, replacing ad-hoc lists of providers in cli.py & setup.py.
catalog.py for easy use of the catalog, including loading known providers.
Add sewer.json info replaces `__version__.py`; sewer_about in lib to access it.
> Documentation; JSON catalogs; library support

- docs/sewer-cli.md
Reverts komuw/sewer#217
I had to scratch my head to figure this one out.  It's rooted in the half-assed "pages" feature github has, and ought to have been `[Aliasing](docs/Aliasing)`, as most of the core docs have been migrated to the web pages view.   Which I still think is better than having wiki pages that aren't versioned in the repo, but it still leaves a lot to be desired.
> Revert "Update sewer-cli.md"

- docs/sewer-as-a-library.md
Picture of the problem:
- Fix errant quote in examples causing …
> Fix errant quote in examples causing highlighting failure
